name: React CI with Cache

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: ./.github/actions/composite-cache-deps
        with:
          node-version: '20.x'
          working-dir: './aplicaciones/aplicaciones'

      - name: Build React app
        run: npm run build
        working-directory: ./aplicaciones/aplicaciones

      # Añade aquí otros pasos como pruebas, despliegue, etc.