name: React CI with Cache

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: ./.github/actions/composite-cache-deps
        with:
          node-version: '20.x'
          working-dir: './.github/aplicaciones/aplicaciones'

      - name: Build React app
        run: npm run build
        working-directory: ./.github/aplicaciones/aplicaciones

      # Añade aquí otros pasos como pruebas, despliegue, etc.
